markerSetName: "GriefPrevention Claims"

# Edit these values to change admin claim colors:
# Format: RRGGBB[AA] (only adminFillColor supports custom alpha values)
adminOutlineColor: "fd6600"
adminFillColor: "fd660096"
# To Change user claim colors edit the default color values in BlueBridgeCore's config or overwrite them here by adding them manually

# Sets the display name for admin regions
adminDisplayName: "Server Claim"

# Set this to true if you want your claims to be displayed in 3D. Not recommended for GriefPrevention as all claims reach to height 255 anyways.
defaultExtrude: false

# If in 2D mode (defaultExtrude: false) this setting will determine if child claims should be displayed a tiny bit higher than their parents to
# ensure that the correct popup is displayed when clicking on them. You can set this to false if you don't like the look of multiple "layers" of markers.
layerChildren: true

